name: DisplayTestPlugin
version: '1'
main: me.simoncrafter.mods.displayTestPlugin.DisplayTestPlugin
api-version: '1.21'
commands:
  cdl:
    description: "The test command for the Crafters display library"